blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/TrisH0x2A/plynk/discussions
    about: Ask questions, share feedback, and discuss ideas with the community.
